AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  mqtt-app

  Sample SAM Template for mqtt-app

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3

Resources:
  MQTTFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      FunctionName: mqtt
      CodeUri: mqtt/
      Handler: app.lambda_handler
      Runtime: python3.13
      Architectures:
      - x86_64
      Environment:
        Variables:
          BUCKET_NAME: "mqtt-key"
          FILE_NAME: "serviceAccountKey.json"
      Policies:
        - S3ReadPolicy:
            BucketName: "mqtt-key"
      Events:
        MqttApi:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /mqtt
            Method: get
            RestApiId: !Ref MqttApiGateway
  MqttApiGateway:
    Type: AWS::Serverless::Api
    Properties:
      Name: "MqttApi"
      StageName: "Prod"
      Cors:
        AllowMethods: "'GET,OPTIONS'"
        AllowHeaders: "'Content-Type,Authorization'"
        AllowOrigin: "'*'"