# Dockerfile
FROM node:18

# Set working directory
WORKDIR /app

# Copy package.json từ thư mục cha
COPY package*.json ./

# Install dependencies
RUN npm install

# Copy source code từ thư mục cha
COPY . .

# Expose port
EXPOSE 3000

# Start the app
CMD ["npm", "run", "dev"]
